services:
  - type: web
    name: shop-backend
    runtime: docker
    plan: free
    region: frankfurt
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://shop-backend.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        value: postgresql://neondb_owner:npg_N9slr2hOIYKQ@ep-raspy-heart-axxo4vd6-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: SESSION_DRIVER
        value: array
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: sync
